import { brand, seoKeywords } from "../lib/tools";

const keywordLine = seoKeywords.join(", ");

export function SeoContent({ tool, home = false }) {
  const title = tool?.title || "YouTube Video Downloader";
  const intro = home
    ? "yt1s.video is built for people who need a clear downloader and creator workflow without confusing popups, misleading buttons, or hidden steps."
    : `${title} is designed for people who want a focused tool page with clear actions, readable options, and practical guidance before they save or process public video content.`;
  return (
    <section className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8">
      <article className="rounded-[2rem] border border-orange-100 bg-white p-6 shadow-xl shadow-orange-100/70 dark:border-white/10 dark:bg-zinc-900 dark:shadow-none sm:p-10">
        <p className="font-black uppercase tracking-[0.28em] text-flame">SEO guide</p>
        <h2 className="mt-3 text-3xl font-black tracking-tight text-ink dark:text-white sm:text-4xl">
          A smooth downloader experience for public YouTube videos, Shorts and audio
        </h2>
        <div className="mt-6 space-y-6 text-sm leading-7 text-gray-600 dark:text-gray-300 sm:text-base sm:leading-8">
          <p>{intro} The goal is simple: paste a link, choose a format, prepare a direct stream, and keep the page responsive on phones, tablets and desktops. This page naturally supports searches such as {keywordLine}, while still explaining the product in normal language instead of repeating keywords without context.</p>
          <p>A good YouTube video downloader should make the first step obvious. The input field accepts a video URL, a Shorts URL, or a valid video ID. The quality selector shows common MP4 options such as 360p, 480p, 720p HD and 1080p full HD when the source can provide them. Audio delivery is handled as M4A because it is widely supported and avoids pretending that every source can be converted to true MP3 instantly. If a format is not available from the source, the interface guides the user back to another option instead of trapping them in a broken loader.</p>
          <p>For mobile users, the form is intentionally stacked: the URL field gets the full width, the paste button stays inside the control, and the format dropdown plus download button are large enough to tap comfortably. On desktop, the same controls align into a compact row so the journey still feels fast. Smooth transitions, clear focus states, and reduced-motion support help the page feel polished without making it heavy. The loader explains what is happening while the system prepares a stream, and the completed state provides a direct download action.</p>
          <p>The current delivery model avoids the older problem of downloading the entire video to the server and then uploading it to cloud storage before the user can save it. Instead, the worker prepares a short-lived stream link and delivers media to the user device when the browser opens that link. This removes upload waiting time, avoids local server video storage, and keeps large files away from Cloudinary limits. It also means final transfer speed depends on the source, the worker network and the user connection, so no page should promise impossible instant downloads for every video.</p>
          <p>Ad placement is also part of the user journey. Google AdSense placeholders are reserved above or between content sections, not over the downloader button. This keeps the main action clean while preserving space for future monetization. When AdSense is approved, the placeholders can be connected with real publisher and slot IDs without changing the page layout. Until then, the placeholders show where ads will appear so spacing and cumulative layout shift can be reviewed before launch.</p>
          <p>Search engines need more than a tool form. They need helpful content, canonical URLs, structured data, robots and sitemap files, legal pages and clear contact details. This site includes WebSite, Organization, WebApplication, FAQ and ItemList schema where relevant. It also includes privacy, terms, DMCA, contact, cookie policy, security.txt and llms.txt routes. Those signals help crawlers understand the purpose of the website and reduce thin-page risk across downloader pages.</p>
          <p>Responsible use matters. yt1s.video is intended for content you own, have permission to use, or are legally allowed to access. The tool does not grant rights to reuse another creator&apos;s work, bypass copyright, or violate platform rules. If a video is private, restricted, unavailable, blocked by the source, or too large for a selected workflow, the page should explain the issue in safe public language without exposing internal credentials, worker details or platform error messages.</p>
          <p>Creators, students, editors and marketers often use tools like this for previews, backups of their own videos, thumbnail research, Shorts workflows, draft metadata, timestamps and quick audio reference files. A quality downloader page should respect that workflow by staying fast, readable and predictable. That is why this page combines a simple form, clear status messages, ad-safe spacing, legal transparency, and structured content designed for both human visitors and search engines.</p>
        </div>
      </article>
    </section>
  );
}

export function LegalLongContent({ page, slug }) {
  return (
    <section className="mx-auto mt-10 max-w-4xl rounded-[2rem] border border-orange-100 bg-white p-6 shadow-xl shadow-orange-100/70 dark:border-white/10 dark:bg-zinc-900 dark:shadow-none sm:p-10">
      <p className="font-black uppercase tracking-[0.28em] text-flame">Policy details</p>
      <h2 className="mt-3 text-3xl font-black tracking-tight text-ink dark:text-white">Detailed {page.title}</h2>
      <div className="mt-6 space-y-6 text-sm leading-7 text-gray-600 dark:text-gray-300 sm:text-base sm:leading-8">
        <p>yt1s.video publishes this {page.title.toLowerCase()} to make the service easier to understand before you paste a URL, prepare a download link, view a thumbnail, generate metadata, or use a creator utility. The website is designed around public YouTube resources and user-provided inputs. We try to keep the downloader journey simple, but legal and privacy information still matters because users, advertisers, search engines and rights holders need clear expectations.</p>
        <p>The service may process a video URL, Shorts URL, video ID, selected quality, temporary job status, request timing, browser information and technical logs required to operate and protect the platform. Completed video files are not intended to remain on local server disk in the current streaming workflow. Temporary stream links expire, and job data is kept only as long as needed for the feature, troubleshooting, abuse prevention and reliability. We avoid displaying internal provider errors, secret names or infrastructure details to public users.</p>
        <p>Cookies and local storage may be used for essential preferences such as cookie consent, interface choices and session-safe status recovery. If analytics or advertising features are enabled in the future, they may use cookies or similar technologies to measure visits, prevent fraud, deliver relevant ads and understand performance. Google AdSense placeholders are included on the site so ad spacing can be reviewed without interrupting the download form. Users can choose essential-only consent from the cookie banner.</p>
        <p>Users are responsible for their own actions. You should only download, convert, inspect or reuse content that you own, have permission to use, or are legally allowed to access. yt1s.video does not claim ownership of third-party content and does not grant copyright permissions. If a rights holder believes a page, tool result, URL or use of the service affects their rights, they can contact {brand.email} with enough detail to review the request.</p>
        <p>For DMCA or copyright notices, include the affected URL, identification of the copyrighted work, proof that you are the rights holder or authorized representative, contact information, a good-faith statement, and a statement that the information is accurate. Incomplete requests may need clarification. Fraudulent notices may be rejected. The review process can include restricting access to a reported URL or taking other reasonable action where appropriate.</p>
        <p>For privacy or cookie questions, include the email address you used to contact us, the specific page or feature involved, and a clear description of the request. We do not ask users to submit private account passwords, YouTube login data, payment information, or sensitive personal material through the downloader form. If you accidentally submit sensitive information, contact us quickly so we can review what can reasonably be removed from operational logs.</p>
        <p>The service can change over time. Source platforms can update delivery rules, videos can disappear, formats can become unavailable, network conditions can change, and ad or analytics tools may require additional disclosures. We may update this policy page to reflect product, legal, operational or advertising changes. The latest version published on yt1s.video controls the public explanation of the service.</p>
        <p>Because yt1s.video includes downloader pages, creator tools, legal pages and advertising placeholders, policy language needs to cover more than one feature. A visitor might use the YouTube video downloader, a short downloader, a thumbnail tool, a title generator or a metadata helper during the same session. Each feature can involve different inputs, but the same basic principles apply: keep only what is needed for the feature, show clear public messages, avoid requesting sensitive account information, and keep ad placements separate from the primary action.</p>
        <p>For cookies, the consent banner records whether the visitor selected essential-only storage, accepted all categories, or dismissed the notice. Essential storage helps remember that choice so the banner does not appear on every page view. If advertising or analytics code is enabled later, additional cookies may be used by those providers according to their own policies. Users can reset choices by clearing site data in the browser, then revisiting yt1s.video to see the consent notice again.</p>
        <p>For advertising, placeholder areas are reserved so the layout remains stable before Google AdSense or another ad provider is approved. The placeholders are not meant to imply that ads are already personalized or active. Once an ad provider is connected, ads may use contextual signals, fraud-prevention checks, consent status and device information. We aim to keep advertisements away from the exact download button and input field so visitors can still understand the main tool without confusion.</p>
        <p>For security, the site publishes security.txt and uses common protective headers such as frame protection, content type protection, referrer limits, permissions policy and HTTPS strict transport security where the hosting platform supports them. These controls do not make any public tool immune to abuse, but they reduce avoidable browser risks and give researchers a clear contact path. Reports should include enough detail to reproduce the issue without sending secrets or private user data.</p>
        <p>For search and AI crawlers, the site publishes sitemap.xml, robots.txt and llms.txt so crawlers can discover public pages and understand the scope of the website. These files describe public resources only. They do not authorize scraping private systems, bypassing API routes, or ignoring the disallow rules for technical endpoints. The public pages are written to explain how the tools work, what limitations exist, and how users can contact the site for policy matters.</p>
        <p>For minors and sensitive content, users should follow local laws and platform rules. yt1s.video does not intentionally ask for age, government identifiers, financial information or private account credentials through the downloader form. If a source platform blocks a video because of age, privacy, availability or rights restrictions, the tool may fail gracefully rather than attempting to force access. That behavior protects the service and sets better expectations for visitors.</p>
        <p>For data retention, temporary operational data may exist in memory, logs, hosting systems or third-party infrastructure for reliability and abuse prevention. The exact retention window can vary by provider and operational need, but the service is not designed as a permanent media locker. Visitors should not treat temporary links, generated outputs or status pages as long-term storage. If a user needs a copy of their own work, they should save it directly to their device using a lawful workflow.</p>
        <p>For international visitors, laws and rights can vary by country. A video that appears public in one region may be unavailable or restricted in another. Users are responsible for checking whether their intended download, reuse, quotation, editing, backup or research activity is allowed where they live. yt1s.video provides tools and information; it does not provide legal advice, copyright clearance, platform permission or professional compliance review.</p>
        <p>If you do not agree with the relevant policies, do not use the website. Continued use of yt1s.video means you understand that the tools are provided for lawful, permission-based workflows and that no downloader can guarantee every video, every quality, or every source will work forever. For support, policy questions, privacy requests, cookie concerns, DMCA notices or partnership questions, contact {brand.email}.</p>
      </div>
    </section>
  );
}
